name: Build artifacts

run-name: ${{ github.actor }} is building artifacts 📦

on:
  release:
    types: [created]

env:

  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  Build_artifacts:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
